const actions = {
    GETEXPECTEDRACEDATA: "GETEXPECTEDRACEDATA",
    GETEXPECTEDRACEDATAOK: "GETEXPECTEDRACEDATAOK",
    GETEXPECTEDBATTLEDATA: "GETEXPECTEDBATTLEDATA",
    GETEXPECTEDBATTLEDATAOK: "GETEXPECTEDBATTLEDATAOK",
    CREATEEXPECTEDBATTLE: "CREATEEXPECTEDBATTLE",
    CREATEEXPECTEDBATTLEOK: "CREATEEXPECTEDBATTLEOK",
}
  
export default actions;  