const actions = {
    GETUSERMANAGEMENTDATA: "GETUSERMANAGEMENTDATA",
    GETUSERMANAGEMENTDATAOK: "GETUSERMANAGEMENTDATAOK",
    UPDATEUSERMANAGEMENTDATA: "UPDATEUSERMANAGEMENTDATA",
    FORMATUSERMANAGEMENTDATA: "FORMATUSERMANAGEMENTDATA",
}
  
export default actions;  