const actions = {
    GETRANKINGDATA: "GETRANKINGDATA",
    GETRANKINGDATAOK: "GETRANKINGDATAOK",
    GETMYPAGEUSERDATA: 'GETMYPAGEUSERDATA',
    GETMYPAGEUSERDATAOK: 'GETMYPAGEUSERDATAOK',
}
  
export default actions;  