const actions = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    SAVE_USERDATA: 'SAVE_USERDATA',
    REGISTER: 'REGISTER',
    UPDATE_USERDATA: 'UPDATE_USERDATA',
  }
  
  export default actions;  