const actions = {
    GETPLACES: 'GETPLACES',
    GETPLACESOK: 'GETPLACESOK',
    NEWRACESTORE: 'NEWRACESTORE',
    UPDATERACESTORE: 'UPDATERACESTORE',
    GETRACESDATA: 'GETRACESDATA',
    GETRACESDATAOK: 'GETRACESDATAOK',
    GETSPECIFICRACEDATA: 'GETSPECIFICRACEDATA',
    INITIALSPECIFICRACEDATA: 'INITIALSPECIFICRACEDATA',
    GETSPECIFICRACEDATAOK: 'GETSPECIFICRACEDATAOK',
    CREATERACERESULT: 'CREATERACERESULT',
    DELETERACEDATA: 'DELETERACEDATA',
}
  
export default actions;  